### ISSUE TITLE
Sync Dockerfile does not build properly

### ISSUE THREAD

**Issue by popcor255** [tektoncd/website#170]
# Expected Behavior
Expected no errors from running dockerfile.

# Actual Behavior
```bash
Traceback (most recent call last):
  File "sync.py", line 144, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "sync.py", line 131, in main
    sync_config_paths = scan(f'{FLAGS.config}')
  File "sync.py", line 120, in scan
    entries = os.scandir(dir_path)
FileNotFoundError: [Errno 2] No such file or directory: '/app/config'
```

# Steps to Reproduce the Problem

```bash
git clone https://github.com/tektoncd/website
cd website
docker build -t tekton-web sync/.
docker run tekton-web
```

/kind bug

**Comment by popcor255** [comment]
Oh derp. A config file needs to be mounted in order for it to work.
