### ISSUE TITLE
Documentation - Variable substitutions links won't work under `Tasks`

### ISSUE THREAD

**Issue by the-zucc** [tektoncd/website#279]
# Expected Behavior

when clicking on either "See the complete list of variable substitutions for Tasks" or "list of fields that accept substitutions", I should be able to be taken to the appropriate page listing the appropriate

# Actual Behavior

404 not found

# Steps to Reproduce the Problem

1. Go on the `Tasks` page in the docs
2. click on the links mentioned

# Additional Info

might want to change the links to point to https://tekton.dev/docs/pipelines/variables/#variables-available-in-a-task & https://tekton.dev/docs/pipelines/variables/#fields-that-accept-variable-substitutions

**Comment by afrittoli** [comment]
@the-zucc thank you for your report

I added a unit test to the sync script for this use case and I could reproduce the issue:
```
======================================================================
FAIL: test_transform_link (__main__.TestSync)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Volumes/Data/go/src/github.com/tektoncd/website/sync/test_sync.py", line 265, in test_transform_link
    self.assertEqual(
AssertionError: '/docs/foo/nested/example.yaml' != '/docs/foo/nested/example.yaml/docs/foo/parallel#withfragment'
- /docs/foo/nested/example.yaml
+ /docs/foo/nested/example.yaml/docs/foo/parallel#withfragment


----------------------------------------------------------------------
```

I will work on a fix now.

**Comment by afrittoli** [comment]
> @the-zucc thank you for your report
> 
> I added a unit test to the sync script for this use case and I could reproduce the issue:
> 
> ```
> ======================================================================
> FAIL: test_transform_link (__main__.TestSync)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/System/Volumes/Data/go/src/github.com/tektoncd/website/sync/test_sync.py", line 265, in test_transform_link
>     self.assertEqual(
> AssertionError: '/docs/foo/nested/example.yaml' != '/docs/foo/nested/example.yaml/docs/foo/parallel#withfragment'
> - /docs/foo/nested/example.yaml
> + /docs/foo/nested/example.yaml/docs/foo/parallel#withfragment
> 
> 
> ----------------------------------------------------------------------
> ```
> 
> I will work on a fix now.

Actually that was a bug in the unit test 😅 
Rewriting seems to be working fine in the unit tests, so I'll dig deeper to see what might be different about the source link: `/variables.md#variables-available-in-a-task`

**Comment by afrittoli** [comment]
The problem seems to be related to the fact that similar links exists on the page, so some of them were being replaced twice.

**Comment by afrittoli** [comment]
Correct links in https://deploy-preview-315--tekton.netlify.app/docs/pipelines/tasks/ : 

- https://deploy-preview-315--tekton.netlify.app/docs/pipelines/variables/#variables-available-in-a-task
- https://deploy-preview-315--tekton.netlify.app/docs/pipelines/variables/#fields-that-accept-variable-substitutions

**Comment by afrittoli** [comment]
@tektoncd/website-maintainers 🙏
